### ISSUE TITLE
Transfer til site til Cloud

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#1]
Flyt nuværende dataplatform til Cloud

**Comment by NicolaiLolansen** [comment]
Hvordan løser vi dette?

Jeg ser følgende mulighed:

Vi laver et nyt site (evt. genbruger cph-opendata.dk, som i øvrigt giver fejl 500 lige nu) og laver en DNS redirect (hvis vi kan det), ellers en simpel site redirect. Datasæt skal oprettes vha. et script som overfører alt data (Tror ikke en harvest kan gøre det, hvis vi vil slette data.kk.dk).
