### ISSUE TITLE
Metadata - unikt id

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#19]

**Comment by suzetteglanz** [comment]
Er ved at løbe liste igennem der sammenligner titler i hhv. data.kk.dk og Metadata-modul, så vores primære ID pt. (Title) er på plads. Herefter går Nicolai videre med etablering af unik ID. Mange af de manglende match skyldes ikke geodata-data i data.kk.dk, da Metadata-modulet kun har indeholdt geodata (KGB-data). Spørgsmålet er om vi skal lable de data der er geodata/KBG data i Metadata-modulet inden vi læser/oprette metadata til  ikke-geodata fra data.kk.dk. Hvis vi ikke gør det, hvor vil Nicolais tjek mellem KBG og Metadata-modulet (der finder nye data i KGB som ikke er registreret i metadata-modulet) ellers kunne fungere?
