### ISSUE TITLE
Filestore integration til Copenhagen Data Tank

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#2]
Til Filestore?
Til Datastore?

**Comment by NicolaiLolansen** [comment]
Filestore plugin er "klart". Har kodet videre på https://github.com/okfn/ckanext-s3filestore og lavet mit eget plugin.

Det er langsomt, men det fungerer op med copenhagen datatank med FileStore

DataStore har jeg ikke undersøgt, men det kræver en rigtig postGres database.
