### ISSUE TITLE
Fejlagtige datoer på datatsæt. Last Updatetd skal være rigtig

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#20]
Datastore bliver ikke opdateret. Datoerne for last updated er derfor forkerte

**Comment by NicolaiLolansen** [comment]
Vi skal tage dette op til revision igen. For selvom last updated nu bliver ændret ved opdatering af datastore, ved vi egentlig ikke om der er indsæt nye rækker.

**Comment by suzetteglanz** [comment]
Snakkede vi ikke om at udkommentere de to CKAN-standard datofelter, da de er misvisende? Og trække feltene om data-ajourføring fra Metadata-modulet?

**Comment by cphflacour** [comment]
@NicolaiMogensen kan du ikke lige skrive 3 sætninger om hvor det var vi rettede? Så har vi det til næste gang.
