### ISSUE TITLE
Ajourføring af datastore - hvilke datasæt er opdateret

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#21]

**Comment by NicolaiLolansen** [comment]
Kald fra GeoServeren har ikke nogen `Content-Length` header, så ingen måde på forhånd at finde fil størrelsen. 

DataPusherens begrænsning på 10mb (Eller højere hvis vi vælger det) kan derfor ikke overholdes. Det resulterer i at vi kan få jobs der kører i rigtig (RIGTIG) lang tid, eksempelvis vil et datasæt på 2-300mb kunne fylde hele køen, og ende ud i flere tusind chunks, med mindre jeg laver noget error handling.

Den gode nyhed er, at hvis jeg kan fikse det, så kan dette problem løses på en forholdsvis pæn måde da det hele kan køres asynkront

**Comment by NicolaiLolansen** [comment]
Har omskrevet datapusheren, til kun at skubbe et vist antal chunks ind i databasen indtil jeg kan finde en bedre måde at håndtere de store sæt på. Nogen nævner at noget udvidelse vil komme til store datasæt, som ikke får Datapusheren til at få time-out.

For nu har jeg lavet et check på et variabelt antal chunks (50 her for at teste). Hvis der er for mange chunks, slettes datasættet fra datastoren.

![image](https://cloud.githubusercontent.com/assets/11227437/16759390/e6ffe60a-4816-11e6-80d9-308536c18ab9.png)

Jeg mangler at omskrive mit script så det kører lokalt i stedet for eksternt, men hooken virker nu.

**Comment by cphflacour** [comment]
Hvad med bare at "aborte" efter chunk N - på den måde ville der stadig være et preview.

**Comment by NicolaiLolansen** [comment]
Problemet med det, er at previewet så afspejler et datasæt som ikke er fuldendt, og det er misvisende. Hvis brugere bruger API'et får de ikke alle data med, og begynder måske at fortolke på et ukomplet sæt.

**Comment by NicolaiLolansen** [comment]
På samme måde har jeg også indtænkt at slette datasæt hvis der opstår HTTP fejl, som igen vil gøre datasættet mangelfuldt, i større eller mindre grad (Men graden af seriøsitet kan vi ikke vide på forhånd)

**Comment by cphflacour** [comment]
Men det er det der er ideen bag et "preview". Jeg mener det er bedre at vise et antal chunks, end slet ikke at vise noget.

Som det er nu kan previewet vise _forkerte_ data, og det er et problem.

**Comment by NicolaiLolansen** [comment]
Har error handlet og testet extension på test, og begynder at skubbe det ud på produktion. 

Kan køre jobbet senere på dagen, og sætte et ugentligt cron-job op

**Comment by NicolaiLolansen** [comment]
Testet og kørt. Lige nu kører jobbet en gang om dagen. Hvis det er for krads ændrer jeg det til en gang om ugen.
