### ISSUE TITLE
Problem med login

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#22]
Der er et eller andet prob lem med at logge ind, hvis der ligger historiske cookies

**Comment by NicolaiLolansen** [comment]
Domænet [www.kk.dk](url) lækker cookies til subdomains, som gør vi ikke kan logge ind.

Helt specifikt er det disse to cookies kombineret der ødelægger ckans `auth_tkt` cookies

`defgo_domainEnterTime` `defgo_domainEnterTime`

Fjernes de, virker login uden problemer. Problemet er at disse cookies bliver sat på igen hvis man besøger [www.kk.dk](url). Jeg tror vi skal oprette en Remedy sag, og bede KS om at holde disse cookies på deres eget domain, så de ikke bløder over til os. Man kan ikke fjerne cookies fra www.example.com hvis man selv befinder sig på *.example.com (Som er vores tilfælde).

![image](https://cloud.githubusercontent.com/assets/11227437/16722692/abbd8684-4748-11e6-9462-8c0172341212.png)

**Comment by cphflacour** [comment]
Nedprioriterer da vi ikke har noget umiddelbart fix og vi kender årsagen.

**Comment by cphflacour** [comment]
Har lagt en tilføjelse til snippets/login_form.html, der henviser til private/inkognito-mode eller cph.opendata.dk, hvis man oplever fejl.

**Comment by cphflacour** [comment]
![image](https://cloud.githubusercontent.com/assets/18282485/16838611/5253d132-49ca-11e6-9493-d35088ba491a.png)
