### ISSUE TITLE
BIF Data

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#25]
ftp hent af bif data fra internt og post til enten ckan eller CDT

**Comment by cphflacour** [comment]
Målet er at overføre en række csv-filer til ressourcer i ckan.

Processen kunne være:
1) Log ind på ftp (med nogle spec. cred., kun tilgængelig indenfor dmz)
2) Hent en navngiven csv-fil
3) Tilføj måned (nummer eller navn) til filen navn
4) Opret den som ny ressource på et givent datasæt
5) gentag 2-5 for ca. 10 filer

Der skal laves en tabel af typen:

filnavn 1 | datasæt guid 1
filnavn 2 | datasæt guid 2
filnavn 3 | datasæt guid 3
...

Ressourcerne opdateres en gang om måneden (2. mandag)

**Comment by NicolaiLolansen** [comment]
Jeg begynder på DMZ siden. Filer er dog i xlsx format, men vi kan sagtens konvertere dem til CSV. 

Påbegynder FTP script der kan hente filer, konvertere dem til CSV og timestampe dem. Hvad vi gør med dem bagefter kan vi tage bagefter

**Comment by NicolaiLolansen** [comment]
Script er klart, pakker det som en extension så vi kan ligge det på produktion med et CRON job

**Comment by NicolaiLolansen** [comment]
Det virker ikke til at serveren har FTP adgang, har ikke hul igennem på serveren.

**Comment by cphflacour** [comment]
Damn! Remedy - ftp for server?

**Comment by NicolaiLolansen** [comment]
Jeg er lige ved at finde ud af om det er generel FTP der mangler (Port 21) eller om det er fordi den ikke kan ramme BIF

**Comment by NicolaiLolansen** [comment]
Port 21 er lukket. Vi skal have en Remedy igang, hvis de skal åbne op.

**Comment by cphflacour** [comment]
Kan vi ikke selv via iptables?

Add these rules to your iptables configuration:

iptables -A INPUT -p tcp --dport 21 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 20 -j ACCEPT

service iptables save
service iptables restart

**Comment by cphflacour** [comment]
Bestilt på remedy 21-08-2016
