### ISSUE TITLE
Socio-økonomiske købehavnerkort

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#27]

**Comment by suzetteglanz** [comment]
Samle alle SØK dataset/ressourcer under en post i data.kk.dk

**Comment by suzetteglanz** [comment]
Afventer at dataset omdøbes i PG (eksternt Dist), da navne er misvisende. Jeg har lavet bud på navngivning, Andy laver den når han er tilbage fra ferie.
