### ISSUE TITLE
Daglig opdatering af brugsstatistik på data.kk.dk

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#29]
Læg et job der opdaterer brugstatistikken på data.kk.dk

**Comment by NicolaiLolansen** [comment]
Har lavet et script der kalder tracking kommandoen, og opdaterer en given resource på et givent datasæt med outputtet. Tester det, og closer hvis det virker.

**Comment by NicolaiLolansen** [comment]
Klar til produktion.

**Comment by NicolaiLolansen** [comment]
Lagt på produktion og testet. Job kører dagligt.

Extension her: https://github.com/NicolaiMogensen/ckanext-updatetracking
