### ISSUE TITLE
SSL Certifikat på site

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#3]
Etablering af certiifikat fra https://letsencrypt.org/

**Comment by cphflacour** [comment]
Afventer at CKAN er klar til SSL

**Comment by NicolaiLolansen** [comment]
Det kan faktisk godt være at CKAN er klar, hvis vi er parate til at hacke lidt i NGINX konfigurationen. 

Se: https://github.com/ckan/ckan/issues/1773
