### ISSUE TITLE
Notifications på data.kk.dk

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#31]
Notifications skal enables.

http://docs.ckan.org/en/latest/maintaining/email-notifications.html

**Comment by cphflacour** [comment]
Problem med opdatering af datasets. Når vi kører refresh på WFS-datasets for at lave preview, trigger vi notification. Kan man lave det på Andre måder?

**Comment by cphflacour** [comment]
Og hvad skal Follow-knappen ellers bruges til?

**Comment by NicolaiLolansen** [comment]
Jeg tror "Follow" knappen giver folk meddelelser i folks Activity Feed, når datasæt opdateres. Hvis notifikationer er slået til får de yderligere en mail.
