### ISSUE TITLE
Mapquest problemer i preview

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#32]
http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

Vi skal have en "plan" eller fundet et alternativ. Kan vi erstatte med vores eget kort? eller google?

**Comment by NicolaiLolansen** [comment]
Kort er lavet, med maks antal features og vores eget baggrundskort.
