### ISSUE TITLE
Internationalisering på data.kk.dk

### ISSUE THREAD

**Issue by NicolaiLolansen** [cphflacour/copenhagen-open-data#34]
Sprogpakken er ikke videre intelligent, der er blanding af svenske, danske og engelske ord.

Dette skal fixes.

**Comment by cphflacour** [comment]
Den ser nu meget intelligent ud :)

Det er ikke mange strenge der skal oversættes.

Filen: 
/usr/lib/ckan/default/src/ckan/ckan/i18n/da_DK/LC_MESSAGES/ckan.po
