### ISSUE TITLE
Datasæt skal sorteres efter "populære" som default

### ISSUE THREAD

**Issue by NicolaiLolansen** [cphflacour/copenhagen-open-data#36]
Det giver mest mening at datasæt sorteres efter hvad der er mest populært. Default er "relevans" men relevans er et løst begreb, og sorterer som oftest i hvad der sidst er opdateret (Som også en en mulighed). 

At ændre til mest populært som default, giver en mere ensformig og spændende liste.

**Comment by AEPSchmitt** [comment]
Default-sortering er ikke relevans selvom det står øverst i "Sortér efter" dropdown menuen.  I stedet bliver datasættene sorteret efter "Sidst modificeret" som default.
Men det giver stadig bedst mening at ændre til sortering efter popularitet.
