### ISSUE TITLE
Sproget skifter til svensk

### ISSUE THREAD

**Issue by AEPSchmitt** [cphflacour/copenhagen-open-data#37]
Sproget skifter til svensk som default. Svensk er slet ikke en valgmulighed på siden. Skiftes til engelsk er oversættelserne korrekte, men ved skift tilbage til dansk er enkelte ord på svensk i stedet.
![image](https://cloud.githubusercontent.com/assets/9079958/17093230/4db186d4-5248-11e6-807f-3574ab01ff8f.png)

**Comment by AEPSchmitt** [comment]
Selv efter server genstart, skifter sproget tilfældigt imellem dansk og svensk når siden opdateres.
https://gyazo.com/0f54625e99a0c181b69e32deac87ba58

**Comment by cphflacour** [comment]
Lavede mindre ændringer i production.ini og genstartede.

Nu ser det ud til det virker.
