### ISSUE TITLE
Nogle previews af csv sidder fast i loading

### ISSUE THREAD

**Issue by AEPSchmitt** [cphflacour/copenhagen-open-data#39]
Ved forsøgt preview af større datasæt som fx Trafikskilte (ca. 20k rækker) færdiggøres loading aldrig:
![image](https://cloud.githubusercontent.com/assets/9079958/17205245/463c6964-54aa-11e6-880f-ae842b5d8d4c.png)

På data.kk.dk kommer følgende fejl i konsollen:
![image](https://cloud.githubusercontent.com/assets/9079958/17205283/7dae5722-54aa-11e6-8b01-aca8c90f2d13.png)

En anden fejlbesked kommer på cph.opendata.dk:
![image](https://cloud.githubusercontent.com/assets/9079958/17205297/97ecc74a-54aa-11e6-8fea-f55e74568527.png)

**Comment by NicolaiLolansen** [comment]
Hvis datasæt er for store / og eller ikke er i datastore, skal de proxies. Hvis de ikke er i datastore, kan de højst sandsynligt ikke proxies. Der skal laves en løsning på samme måde som ved geoJSON
