### ISSUE TITLE
Etabl. af CDT webservice internt

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/copenhagen-open-data#41]
Vi skal have etableret vores CDT service på 
ks-ckan-app01.ks.kk.dk

og eventuelt et testmiljø på:
ks-ckan-app02.ks.kk.dk

**Comment by cphflacour** [comment]
CDT Copenhagen Data Tank

Har du de logins du skal bruge?

**Comment by AEPSchmitt** [comment]
I min liste af logins står der " “bu1g” root adgang via Koncernservice" under de to domæner.
Skal jeg kontakte koncernservice for at få et login?

**Comment by cphflacour** [comment]
Eller Nicolai

**Comment by AEPSchmitt** [comment]
Okay, den tager jeg med ham på onsdag.
