### ISSUE TITLE
Store datasæt fejler i datastore

### ISSUE THREAD

**Issue by AEPSchmitt** [cphflacour/copenhagen-open-data#44]
F. eks. kan:
http://data.kk.dk/dataset/parkomat-transaktioner/resource/660e19fa-8838-4a5c-9495-0d7f94fab51e
Hverken previewes eller downloades.

**Comment by NicolaiLolansen** [comment]
Det er meningen. Store sæt skal ikke læses ind i datastoren, da det tager for lang tid ved daglig opdatering. Til gengæld skal previewet kunne fungere alligevel.
